name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    if: github.event.release.target_commitish == 'main'

    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - name: Linux-x86_64
            platform: 'ubuntu-latest' # for Tauri v1 you could replace this with ubuntu-20.04.
            target: x86_64-unknown-linux-gnu
            arch: x64

          - name: Linux-ARM64
            platform: 'ubuntu-24.04-arm'
            target: aarch64-unknown-linux-gnu
            arch: arm64

          - name: macOS-Apple
            platform: 'macos-latest' # for Arm based macs (M1 and above).
            target: aarch64-apple-darwin
            arch: arm64

          - name: macOS-Intel
            platform: 'macos-latest' # for Intel based macs.
            target: x86_64-apple-darwin
            arch: x64

          - name: Windows-x86_64
            platform: 'windows-latest'
            target: x86_64-pc-windows-msvc
            arch: x64

          - name: Windows-Arm
            platform: 'windows-11-arm'
            target: aarch64-pc-windows-msvc
            arch: arm64

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest' || matrix.platform == 'ubuntu-24.04-arm'
        # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
        # If you want to use the tray icon you need to install "libappindicator3-dev"
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential \
            curl \
            wget \
            file \
            libwebkit2gtk-4.1-dev \
            libssl-dev \
            librsvg2-dev \
            patchelf \
            xdg-utils

          if [ -x /bin/xdg-open ] && [ ! -e /usr/bin/xdg-open ]; then
            sudo ln -s /bin/xdg-open /usr/bin/xdg-open
          fi

          command -v xdg-open
          ls -l /usr/bin/xdg-open

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: '. -> target'

      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: 'npm'

      - name: Install frontend dependencies
        # If you don't have `beforeBuildCommand` configured you may want to build your frontend here too.
        run: npm ci

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
#          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          projectPath: apps/desktop
          tagName: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
          releaseName: 'v__VERSION__' # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: false
          prerelease: false
          args: --target ${{ matrix.target }}

      - name: Build Portable Binaries (Windows)
        if: ${{ matrix.platform == 'windows-latest' || matrix.platform == 'windows-11-arm' }}
        shell: pwsh
        run: |
          cd apps/desktop
          cargo build --release --target ${{ matrix.target }}
          cd ../..
          Move-Item "./target/${{ matrix.target }}/release/Keira4.exe" "./target/${{ matrix.target }}/release/Keira4_${{ github.ref_name }}_${{ matrix.arch }}-portable.exe"

      - name: Upload Portable Binaries (Windows)
        if: ${{ matrix.platform == 'windows-latest' || matrix.platform == 'windows-11-arm' }}
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          Get-ChildItem -Force ./target
          Get-ChildItem -Force ./target/${{ matrix.target }}
          Get-ChildItem -Force ./target/${{ matrix.target }}/release
          gh release upload ${{ github.ref_name }} ./target/${{ matrix.target }}/release/Keira4_${{ github.ref_name }}_${{ matrix.arch }}-portable.exe --clobber
